### ISSUE TITLE
criteria for fcd,fc,sc for schemes 15,17,18,19

### ISSUE THREAD

**Issue by sugy17** [Rushyanth111/Semester-Stats#15]
-passed in all subjects in the semester.
-FCD : 70 % and above in, total marks .
-FC : 60% and above but less than 70% ,in total marks.
-SC: 40% and above but less than 60% ,in total marks.
The above applies to all subjects(including labs) and students, irrespective of their scheme or batch. 

Additional note: Scheme 12 had total marks of 125.(All info reagrding this will be covered in documentation of csv format)

**Comment by Rushyanth111** [comment]
Is Scheme 12 required? Since it's 2020, they should have all passed else they will be removed from the program entirely. VTU allows only 8 years of education, after which they are let go.

**Comment by sugy17** [comment]
That was intended to bring out the point that total marks could be more or less than 100, in the future.

**Comment by Rushyanth111** [comment]
I'll create a new Algorithm Issue that addresses the Calculation for this.

**Comment by Rushyanth111** [comment]
Implemented. And Fixed.
