### ISSUE TITLE
[Feature] Inclusion of diploma students

### ISSUE THREAD

**Issue by sugy17** [Rushyanth111/Semester-Stats#16]
-Diploma students are to be analysed along with other students in the scheme(/semester) per dept and are to be included in the report(docx file).
-Subjects that are common to non diploma and diploma students are only to be included in the report.
-Decide in which file should they be placed.

**Comment by Rushyanth111** [comment]
Is there a concerte method to determine the diploma students? 

> Subjects that are common to non diploma and diploma students

Elaborate on this? What are the students common to non diploma and diploma students?

**Comment by sugy17** [comment]
-Diploma students are assigned usns 1crXXXX400 and above.

-The diploma specific subjects consist a 'DIP' in the subject code.

-For instance,1cr18cs401 would write all the subjects 1cr17cs154 would write in a sem.1cr18cs401 would write extra subjects that would consist a 'DIP' substring in them.Hence the subjects that dont contain 'DIP' are the common subjects, that are to be inlcuded in the report.


-usually XXMATDIP3X and XXMATDIP4X are the only extra subjects that dip peeps write.May change in future.

**Comment by Rushyanth111** [comment]
Is this Universal Under VTU?

**Comment by Rushyanth111** [comment]
https://studychacha.com/discuss/122626-vtu-students-usn.html

**Comment by Rushyanth111** [comment]
Please take a look at the above and see if this holds?

**Comment by sugy17** [comment]
https://rvce.edu.in/be-usn-2018-regular-lateral

Yes ,i belive it is universal.
The DIP students are called as lateral entry students and the rest are called as regular srtudents.Savitha maam has confirmed.
And as of the subject code, Savitha maam confirmed that DIP will be mentioned in the code,and that there is only MATDIP which is the extra subject they will be writing in 3rf and 4th sems.

**Comment by Rushyanth111** [comment]
That is conclusive, Marking all 400> Students as Diploma or Lateral Entry.

**Comment by Rushyanth111** [comment]
It would seem that the diploma students are automatically counted without having to do much within the code. There is no special case for the diploma students. Just the semester they have attended, which would start from 3 onward. This might become a problem when the algorithm for USN change is written.
