### ISSUE TITLE
[Algorithm] Figure out the subject maximum.

### ISSUE THREAD

**Issue by Rushyanth111** [Rushyanth111/Semester-Stats#33]
@sugy17 There's an issue where some of the subjects have 50 marks as their total, this causes a small bug in the processing unit  that tries to determine when there's a subject that is marked as 50.

This leads to algorithmic mistakes when calculating FCD, FC, SC, etc.

**Comment by sugy17** [comment]
Subject details are now avaliable on vtu's website.How about I scrap them too and send to an endpoint?

**Comment by Rushyanth111** [comment]
Yeah, You'll need to come up with a method/format. I'm currently working on improving the existing model, which should be even more extensible for future updates.

**Comment by Rushyanth111** [comment]
Closed on account of new Assumptions.
