### ISSUE TITLE
[Feature] Watchable Folder -- Ensure that the folder is being watched to add new data. 

### ISSUE THREAD

**Issue by Rushyanth111** [Rushyanth111/Semester-Stats#9]
- When new data is placed into the folder, ensure that there is a watch function that captures the data.

**Comment by sugy17** [comment]
could u perhaps put it in a simpler way with some more details or give an example?

**Comment by Rushyanth111** [comment]
Not Required anymore, API is now exposing the new `/upload/file` for automatica uploads.
